<?php
print ("<!DOCTYPE html>\n<html>\n<head>\n<title>오클리 TEST</title>\n<meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">
    <link rel='stylesheet' type='text/css' href='css/font/ubuntu.css'>\n");
print("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic+Coding&display=swap\" rel=\"stylesheet\">");
//echo "<h3> PHP List All Session Variables</h3>";
//foreach ($_SESSION as $key=>$val)
//    echo $key." ".$val."<br/>";
//echo "<hr>";