<?php session_start();
include("sessionheader.inc");
include("pageheader.inc");

// Fetch the page data
$sql = "SELECT voxcabs.imgName, voxcabs.svgData, tbl_student_voxcab.voice_id, tbl_student_voxcab.id
FROM tbl_student_voxcab INNER JOIN voxcabs ON (tbl_student_voxcab.voxcab_id = voxcabs.id) 
WHERE tbl_student_voxcab.start_date<Now() AND tbl_student_voxcab.end_date>Now() AND tbl_student_voxcab.student_id='" . $_SESSION['studid'] . "' 
ORDER BY tbl_student_voxcab.start_date LIMIT 1;";
$query = mysqli_query($conn, $sql);

list($imgName, $svgData, $voiceId, $id) = mysqli_fetch_row($query);

?>
<link rel="stylesheet" href="css/voxcab.css">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vocab Trainer</title>
<script src="js/voxcab.js"></script>
</head>

<script>
    window.onload = function () {
        audio = document.getElementById('bob');
        populateWordlist("");
        showToast();
    }
</script>

<body>
<!-- Image Map Generated by http://www.image-map.net/ -->
<div id="container" style="position:absolute">
    <?php
    //  print($svgData);
    $newString = str_replace("onclick=" . chr(34) . "check", "onclick=" . chr(34) . "playSprite", $svgData);
    print($newString);
    ?>
</div>

<div id="snackbar" class="toast">some text</div>

<audio preload id="bob">
    <source src="audio/blanket.wav" type="audio/wav">
</audio>

<?php
print "<input id='id' type='hidden' value='".$id."'>";
?>

</body>
</html>