<?php session_start();
include("sessionheader.inc");
include("pageheader.inc");
// Fetch the page data
$sql = "SELECT voxcabs.imgName, voxcabs.svgData, tbl_student_voxcab.voice_id
FROM tbl_student_voxcab INNER JOIN voxcabs ON (tbl_student_voxcab.voxcab_id = voxcabs.id) AND (tbl_student_voxcab.voxcab_id = voxcabs.id)
WHERE tbl_student_voxcab.start_date<Now() AND tbl_student_voxcab.end_date>Now()
ORDER BY tbl_student_voxcab.start_date LIMIT 1;";
$query = mysqli_query($conn, $sql);

list($imgName, $svgData, $voiceId) = mysqli_fetch_row($query);

?>
    <link rel="stylesheet" href="css/voxcab.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vocab Trainer</title>
    <script src="js/voxcab.js"></script>
</head>
<body>
<!-- Image Map Generated by http://www.image-map.net/ -->
<div id="container" style="position:absolute">
<?php
//  print($svgData);
  $newString = str_replace("onclick=".chr(34)."check", "onclick=".chr(34)."playSprite", $svgData);
  print($newString);
    ?>

    // hard-coded while beginning, delete now that Db input is implemented
<!--    <svg version="1.1" viewBox="0 0 1024 576" preserveAspectRatio="xMinYMin meet">-->
<!--            <image href="img/1587352.jpg"></image>-->
<!--        <rect x="11" y="223" fill="#fff" opacity="0" width="120" height="153" onclick="playSprite('lamp')"/>-->
<!--        <rect x="893" y="244" fill="#fff" opacity="0" width="56" height="51" onclick="playSprite('lamp')"/>-->
<!--        <polygon points="404,458,552,403,759,506,675,573,578,574" opacity="0" fill="#fff" onclick="playSprite('rug')"/>-->
<!--        <polygon points="323,29,314,277,538,255,542,96" opacity="0" fill="#fff" onclick="playSprite('window')"/>-->
<!--        <polygon points="722,284,858,305,877,263,742,249" opacity="0" fill="#fff" onclick="playSprite('pillows')"/>-->
<!--        <polygon points="552,333,801,441,873,356,872,329,856,305,704,279,568,308" opacity="0" fill="#fff"-->
<!--                 onclick="playSprite('blanket')"/>-->
<!--        <polygon points="149,32,96,117,86,166,149,174,161,116,200,97,201,40" opacity="0" fill="#fff"-->
<!--                 onclick="playSprite('pictures')"/>-->
<!--        <rect x="165" y="129" fill="#fff" opacity="0" width="83" height="55" onclick="playSprite('football')"/>-->
<!--        <rect x="589" y="138" fill="#fff" opacity="0" width="67" height="134" onclick="playSprite('guitar')"/>-->
<!--        <circle cx="953" cy="318" r="23" fill="#fff" opacity="0" onclick="playSprite('clock')"/>-->
<!--    </svg>-->
</div>

<div id="snackbar">some text</div>

<audio preload id="bob">
    <source src="audio/blanket.wav" type="audio/wav">
</audio>

<script>



    // window.onload = function(){
    //     showToast();
    // };
</script>

</body>
</html>