<?php session_start();
include("sessionheader.inc");
include("pageheader.inc");
// Fetch the page data

$sql = "SELECT voxcabs.imgName, voxcabs.svgData, tbl_student_voxcab.voice_id, tbl_student_voxcab.id, tbl_student_voxcab.start_date, tbl_student_voxcab.end_date, 
       tbl_student_voxcab.score, tbl_student_voxcab.time, tbl_student_voxcab.num_perfect
FROM tbl_student_voxcab INNER JOIN voxcabs ON (tbl_student_voxcab.voxcab_id = voxcabs.id) 
WHERE tbl_student_voxcab.start_date<Now() AND tbl_student_voxcab.end_date>Now() AND tbl_student_voxcab.student_id='" . $_SESSION['studid'] . "' 
ORDER BY tbl_student_voxcab.start_date LIMIT 1;";
$query = mysqli_query($conn, $sql);

list($imgName, $svgData, $voiceId, $id, $startDate, $endDate, $score, $time, $numPerfect) = mysqli_fetch_row($query);

?>

<link rel="stylesheet" href="css/voxcab.css">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vocab Trainer</title>
<script src="js/voxcab.js"></script>
</head>
<script>
    window.onload = function () {
        audio = document.getElementById('bob');
        populateWordlist("test");
        // showToast();
    }
</script>
<body>
<!-- Image Map Generated by http://www.image-map.net/ -->

<div id="container" style="position:absolute">
    <?php
    print($_POST['studid']);
    $newString = str_replace("onclick=" . chr(34) . "check", "onclick=" . chr(34) . "check", $svgData);
    print($newString);
    ?>
</div>
<button id="start_button" onclick="doNext();">START</button>


<audio preload id="bob">
    <source src="audio/blanket.wav" type="audio/wav">
</audio>
<?php
print "<input id='id' type='hidden' value='".$id."'>";
print "<input id='startDate' type='hidden' value='".$startDate."'>";
print "<input id='endDate' type='hidden' value='".$endDate."'>";
print "<input id='score' type='hidden' value='".$score."'>";
print "<input id='time' type='hidden' value='".$time."'>";
print "<input id='numPerfect' type='hidden' value='".$numPerfect."'>";
?>

<div id="testSnackbar"  class="toast">some text</div>

</body>
</html>

